### ISSUE TITLE
How to include a sc2 file as a splash screen in a single cas file?

### ISSUE THREAD

**Issue by DarwinNE** [reidrac/mkcas#1]
Hi @reidrac 
   thanks for your wonderful tool, it was exactly what I was searching for. I have a question: I hope here is the right place where to ask and please excuse me in advance as I am a complete newbie in the MSX world.

I have a program that I would like to load with a splash screen that I'd like to show while loading. I thought I can write a simple basic program in a first file called msxl.bas:
~~~~
1 print "The Queen's Footsteps"
2 print "Loading"
3 screen 2
4 bload "CAS:",s
5 bload "CAS:",r
~~~~

I then have two files, the first one (called `splash.sc2`) contains the image. The second, called `program` contains my program. I tried assembling them together with mkcas:

~~~~
mkcas.py my_game.cas ascii MSXl.bas 
mkcas.py --add --addr 0x0 my_game.cas binary splash.sc2
mkcas.py --add --addr 0x8000 --exec 0x8000  my_game.cas binary program 
~~~~

but this does not seem to work (nothing is shown, but the game starts). I could find the configuration of my program to be loaded and run (hence the `--addr` and `--exec`), but I am not sure how I can configure the second command for the `splash.sc2` file (obtained with PPolizei, btw) so that it is charged on the screen.

Have you already used your tool to obtain something similar?

Cheers,
D.

**Comment by reidrac** [comment]
The parameter S is used to load the contents to VRAM but **only from disk**, so it won't work in cassette.

I don't know if you can find an example in basic to load the image to RAM and then upload it to the VDP; I use my own loader in assembler.

**Comment by DarwinNE** [comment]
Thank you!

**Comment by reidrac** [comment]
If you don't find a solution, let me know and I can make a loader for you.

**Comment by DarwinNE** [comment]
Thank you very much!
I'm trying to study how to use VDC, it should not be too difficult to code a simple loader in C, I have already done that with other computers.
I may probably come to you with some stupid questions, though :-)
Cheers,
D.

**Comment by reidrac** [comment]
Give me a couple of days. It shouldn't be too difficult to make something generic you can easily use without even touching an assembler.

**Comment by DarwinNE** [comment]
Thank you very much!
That would be much appreciated.
Cheers,
D.
